# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: KinoDev.Shared Build and Publish NuGet Package to GitHub Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Pack NuGet package
      run: dotnet pack KinoDev.Shared.csproj --configuration Release --no-build --output ./nupkg

    - name: Publish NuGet package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_KEY }}
      run: |
        dotnet nuget push ./nupkg/*.nupkg \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key $GITHUB_TOKEN     
